
autoload -Uz compinit && compinit
compinit

DIR=~/.northvolt/stuff.zsh

if [[ -f "$DIR" ]]
then 
	. ~/.northvolt/stuff.zsh
fi

export PATH=$PATH:/Users/jveiga/Library/Python/3.8/bin

. $HOME/.asdf/asdf.sh

export RUSTFLAGS='-C opt-level=3 -C target-cpu=native'
source ~/.cargo/env

alias vim=nvim

eval "$(zoxide init zsh)"

export PATH=$PATH:~/.local/bin

eval "$(starship init zsh)"

source ~/.antigen.zsh
antigen use oh-my-zsh
antigen bundle git

alias gfm="gf && gm"

antigen apply
. ~/.skim_key_bindings.zsh

alias sed=gsed

alias dc=docker-compose
