# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '/home/jveiga/.zshrc'

autoload -Uz compinit
compinit
autoload -Uz promptinit
promptinit
prompt adam2
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
#set -o vi
#bindkey -e
# End of lines configured by zsh-newuser-install
alias ls='ls -h --color=auto'
alias rm='rm -v'
alias cp='cp -v'
alias ssh='ssh -vv'
alias casa='ssh casa'
alias tania='ssh tania'
alias sftp='sftp -vv'
alias mv='mv -v'

export EDITOR='vim'
#export EDITOR='gvim -f'
export SVN_EDITOR='vim -f -c "4,\$!cut -c-5 --complement | xargs svn diff --no-diff-deleted -x --ignore-eol-style" -c "set syntax=diff" +0'
# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline0
#export TERM=xterm-256color
#[ -z "$TMUX" ] && export TERM=xterm-256color

